[package]
name = "bfb"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.10", features = ["derive"] }
ctrlc = "3.4.1"
futures = "0.3.29"
indicatif = "0.17.7"
memmap2 = "0.9.0"
qdrant-client = "1.7"
rand = "0.8.5"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.34.0", features = ["full"] }
tokio-stream = "0.1.14"
uuid = { version = "1.6.1", features = ["serde", "v4"] }
