[package]
name = "bfb"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.25", features = ["derive"] }
ctrlc = "3.2.3"
futures = "0.3.25"
indicatif = "0.17.2"
qdrant-client = "0.11.1"
rand = "0.8.5"
tokio = { version = "~1.21", features = ["full"] }
uuid = "1.2.1"
